server:
  port: 8002
mybatis:
  type-aliases-package: com.liyiruo.springcloud.entites
  config-location: classpath:mybatis/cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservice-product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: '!QAZ2wsx'
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: http://${spring.application.name}:${server.port}
    prefer-ip-address: true
