server:
  port: 7001

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

zuul:
  routes:
    provider-product:
      path: /product/**
      serviceId: microservice-product
      stripPrefix: false
#      如果有多个需要路由，如上继续添加 即可
#    provider-order:
#      path: /product/**
#      serviceId: miroservice-product
#      stripPrefix: false

