server:
  port: 5001

spring:
  application:
#    name: microservice-config-application  #github上的配置名称
    name: microservice-config-product
#    name: microservice-config-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liyiruo/microservice-cloud-config.git
#          uri: https://github.com/liyiruo/microservice-cloud-config.git


