server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/cfg.xml
  type-aliases-package: com.liyiruo.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
    name: microservice-product  #这个很重要，以后服务与服务之间互相调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: '!QAZ2wsx'
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #单机版服务注册中心
#      defaultZone: http://localhost:6001/eureka
      #集群版Eureka 服务注册中心
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

  instance:
    instance-id: ${spring.application.name}:${server.port} #指定实例ID 就不会显示主机名了
    prefer-ip-address: true #访问路经可以显示ip地址